apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ss-pvc
  namespace: minio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rclone
  volumeMode: Filesystem
